language: bash
#
# Either xenial or bionic are necessary for the Snap Add-on.
#
dist: xenial
virt: vm
os: linux
arch: amd64

addons:
  apt:
    packages:
      - shunit2
  snaps:
    - name: shfmt
script:
  - make test
  - shfmt -i 2 -bn -ci -d src/gepsh.sh
