language: bash
#
# Either xenial or bionic are necessary for the Snap Add-on.
#
dist: xenial
virt: lxt
os: linux
arch: amd64

install:
  - wget -c https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64
  - rm -f /usr/bin/shfmt
  - sudo install -m0755 shfmt_v3.5.1_linux_amd64 /usr/bin/shfmt

addons:
  apt:
    packages:
      - shunit2

script:
  - shfmt --version
  - make test
